-- BugYou Database Setup Script v5.0
-- Fixed schema with independent sequences for each table

-- Drop all tables
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS python_basic CASCADE;
DROP TABLE IF EXISTS python_intermediate CASCADE;
DROP TABLE IF EXISTS python_advanced CASCADE;
DROP TABLE IF EXISTS javascript_basic CASCADE;
DROP TABLE IF EXISTS javascript_intermediate CASCADE;
DROP TABLE IF EXISTS javascript_advanced CASCADE;
DROP TABLE IF EXISTS java_basic CASCADE;
DROP TABLE IF EXISTS java_intermediate CASCADE;
DROP TABLE IF EXISTS java_advanced CASCADE;
DROP TABLE IF EXISTS cpp_basic CASCADE;
DROP TABLE IF EXISTS cpp_intermediate CASCADE;
DROP TABLE IF EXISTS cpp_advanced CASCADE;

-- Create minimal users table for created_by reference
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL
);

-- Create challenge tables with independent sequences
-- Each table will have its own sequence starting from 1

CREATE TABLE python_basic (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE python_intermediate (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE python_advanced (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE javascript_basic (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE javascript_intermediate (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE javascript_advanced (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE java_basic (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE java_intermediate (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE java_advanced (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE cpp_basic (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE cpp_intermediate (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
);

CREATE TABLE cpp_advanced (
    challenge_id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    problem_statement TEXT NOT NULL,
    buggy_code TEXT NOT NULL,
    reference_solution TEXT,
    solution_explanation TEXT,
    hint_1 TEXT,
    hint_2 TEXT,
    hint_3 TEXT,
    learning_objectives TEXT,
    max_score INTEGER DEFAULT 10,
    test_case_1_input TEXT NOT NULL,
    test_case_1_expected TEXT NOT NULL,
    test_case_2_input TEXT NOT NULL,
    test_case_2_expected TEXT NOT NULL,
    test_case_3_input TEXT NOT NULL,
    test_case_3_expected TEXT NOT NULL,
    test_case_4_input TEXT,
    test_case_4_expected TEXT,
    test_case_5_input TEXT,
    test_case_5_expected TEXT,
    hidden_test_1_input TEXT,
    hidden_test_1_expected TEXT,
    hidden_test_2_input TEXT,
    hidden_test_2_expected TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(user_id),
    success_rate DECIMAL(5,2) DEFAULT 0.0,
    avg_attempts DECIMAL(5,2) DEFAULT 0.0
); 