-- Sample data for BugYou challenges
-- Insert sample challenges into each table with explicit challenge_id values

-- Python Basic Challenges
INSERT INTO python_basic (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Find Maximum Number', 'Write a function that finds the maximum number in a list. The function should handle edge cases like empty lists and lists with negative numbers.', 'def find_max(numbers):\n    max_num = 0\n    for num in numbers:\n        if num > max_num:\n            max_num = num\n    return max_num', 'def find_max(numbers):\n    if not numbers:\n        return None\n    max_num = numbers[0]\n    for num in numbers:\n        if num > max_num:\n            max_num = num\n    return max_num', 'The bug is in the initialization of max_num. Starting with 0 fails for lists with only negative numbers. We should initialize with the first element of the list.', 'What happens when all numbers in the list are negative?', 'Try initializing max_num with the first element of the list instead of 0.', 'Consider what happens with an empty list - should we return None or 0?', 'Students will learn about proper variable initialization and edge case handling.', 10, '[1, 2, 3, 4, 5]', '5', '[-1, -2, -3]', '-1', '[]', 'None'),
(2, 'Count Even Numbers', 'Write a function that counts the number of even numbers in a list.', 'def count_even(numbers):\n    count = 0\n    for i in range(len(numbers)):\n        if numbers[i] % 2 == 0:\n            count += 1\n        return count', 'def count_even(numbers):\n    count = 0\n    for i in range(len(numbers)):\n        if numbers[i] % 2 == 0:\n            count += 1\n    return count', 'The bug is in the indentation of the return statement. It should be outside the for loop, not inside it.', 'Look at the indentation of the return statement.', 'The return statement should be at the same level as the for loop, not inside it.', 'Check if the return statement is properly aligned.', 'Students will learn about proper indentation and loop control flow.', 10, '[1, 2, 3, 4, 5, 6]', '3', '[2, 4, 6, 8]', '4', '[1, 3, 5]', '0');

-- Python Intermediate Challenges
INSERT INTO python_intermediate (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Remove Duplicates', 'Write a function that removes duplicate elements from a list while preserving the order.', 'def remove_duplicates(lst):\n    result = []\n    for item in lst:\n        if item not in result:\n            result.append(item)\n    return result', 'def remove_duplicates(lst):\n    if not lst:\n        return []\n    result = []\n    for item in lst:\n        if item not in result:\n            result.append(item)\n    return result', 'The function is mostly correct, but it should handle the case of an empty list explicitly.', 'What happens when the input list is empty?', 'Add a check for empty list at the beginning.', 'Consider edge cases like None or empty list.', 'Students will learn about edge case handling and list operations.', 10, '[1, 2, 2, 3, 4, 4, 5]', '[1, 2, 3, 4, 5]', '[1, 1, 1]', '[1]', '[]', '[]');

-- Python Advanced Challenges
INSERT INTO python_advanced (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Binary Search', 'Implement binary search to find a target number in a sorted array.', 'def binary_search(arr, target):\n    left, right = 0, len(arr)\n    while left < right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid\n        else:\n            right = mid\n    return -1', 'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1', 'The bugs are: 1) right should be len(arr) - 1, 2) loop condition should be <=, 3) left should be mid + 1, 4) right should be mid - 1.', 'Check the initial value of right.', 'Look at the loop condition and update logic.', 'Consider how the search space should be reduced.', 10, '[1, 2, 3, 4, 5]', '2', '[1, 3, 5, 7, 9]', '4', '[1, 2, 3, 4, 5]', '-1');

-- JavaScript Basic Challenges
INSERT INTO javascript_basic (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Calculate Sum', 'Write a function that calculates the sum of all numbers in an array. Handle edge cases properly.', 'function calculateSum(arr) {\n    let sum = 0;\n    for (let i = 0; i <= arr.length; i++) {\n        sum += arr[i];\n    }\n    return sum;\n}', 'function calculateSum(arr) {\n    if (!arr || arr.length === 0) {\n        return 0;\n    }\n    let sum = 0;\n    for (let i = 0; i < arr.length; i++) {\n        sum += arr[i];\n    }\n    return sum;\n}', 'The bug is in the loop condition. Using <= instead of < causes an off-by-one error, accessing an undefined element.', 'What happens when i equals arr.length?', 'Arrays are zero-indexed. If length is 5, valid indices are 0-4, not 0-5.', 'Change <= to < in the for loop condition.', 10, '[1, 2, 3, 4, 5]', '15', '[10, 20, 30]', '60', '[]', '0');

-- JavaScript Intermediate Challenges
INSERT INTO javascript_intermediate (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Reverse String', 'Write a function that reverses a string without using the built-in reverse method.', 'function reverseString(str) {\n    let reversed = "";\n    for (let i = 0; i < str.length; i++) {\n        reversed = str[i] + reversed;\n    }\n    return reversed;\n}', 'function reverseString(str) {\n    if (!str) {\n        return "";\n    }\n    let reversed = "";\n    for (let i = 0; i < str.length; i++) {\n        reversed = str[i] + reversed;\n    }\n    return reversed;\n}', 'The function should handle null or undefined input.', 'What happens when the input is null or undefined?', 'Add a check for null/undefined input.', 'Consider edge cases like empty string.', 10, '"hello"', '"olleh"', '"world"', '"dlrow"', '""', '""');

-- JavaScript Advanced Challenges
INSERT INTO javascript_advanced (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Find Longest Substring', 'Write a function that finds the length of the longest substring without repeating characters.', 'function lengthOfLongestSubstring(s) {\n    let maxLength = 0;\n    let start = 0;\n    let charMap = {};\n    \n    for (let i = 0; i < s.length; i++) {\n        if (charMap[s[i]] >= start) {\n            start = charMap[s[i]] + 1;\n        }\n        charMap[s[i]] = i;\n        maxLength = Math.max(maxLength, i - start + 1);\n    }\n    return maxLength;\n}', 'function lengthOfLongestSubstring(s) {\n    if (!s) {\n        return 0;\n    }\n    let maxLength = 0;\n    let start = 0;\n    let charMap = {};\n    \n    for (let i = 0; i < s.length; i++) {\n        if (charMap[s[i]] >= start) {\n            start = charMap[s[i]] + 1;\n        }\n        charMap[s[i]] = i;\n        maxLength = Math.max(maxLength, i - start + 1);\n    }\n    return maxLength;\n}', 'The function should handle null or undefined input.', 'What happens when the input is null or undefined?', 'Add a check for null/undefined input.', 'Consider edge cases like empty string.', 10, '"abcabcbb"', '3', '"bbbbb"', '1', '""', '0');

-- Java Basic Challenges
INSERT INTO java_basic (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Find Minimum', 'Write a function that finds the minimum number in an array. Handle edge cases properly.', 'public static int findMin(int[] numbers) {\n    int min = 0;\n    for (int i = 0; i < numbers.length; i++) {\n        if (numbers[i] < min) {\n            min = numbers[i];\n        }\n    }\n    return min;\n}', 'public static int findMin(int[] numbers) {\n    if (numbers == null || numbers.length == 0) {\n        throw new IllegalArgumentException("Array cannot be null or empty");\n    }\n    int min = numbers[0];\n    for (int i = 1; i < numbers.length; i++) {\n        if (numbers[i] < min) {\n            min = numbers[i];\n        }\n    }\n    return min;\n}', 'The bug is in the initialization of min. Starting with 0 fails for arrays with only positive numbers. We should initialize with the first element.', 'What happens when all numbers in the array are positive?', 'Try initializing min with the first element of the array instead of 0.', 'Start the loop from index 1 since we already have the first element as min.', 10, '{1, 2, 3, 4, 5}', '1', '{10, 5, 8, 2}', '2', '{7, 7, 7}', '7');

-- Java Intermediate Challenges
INSERT INTO java_intermediate (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Check Prime Number', 'Write a function that checks if a number is prime.', 'public static boolean isPrime(int n) {\n    if (n <= 1) {\n        return false;\n    }\n    for (int i = 2; i < n; i++) {\n        if (n % i == 0) {\n            return false;\n        }\n    }\n    return true;\n}', 'public static boolean isPrime(int n) {\n    if (n <= 1) {\n        return false;\n    }\n    if (n == 2) {\n        return true;\n    }\n    if (n % 2 == 0) {\n        return false;\n    }\n    for (int i = 3; i <= Math.sqrt(n); i += 2) {\n        if (n % i == 0) {\n            return false;\n        }\n    }\n    return true;\n}', 'The function can be optimized by checking only up to square root and skipping even numbers.', 'Do we need to check all numbers up to n?', 'We only need to check up to the square root of n.', 'We can skip even numbers after checking 2.', 10, '7', 'true', '4', 'false', '1', 'false');

-- Java Advanced Challenges
INSERT INTO java_advanced (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Merge Sort', 'Implement merge sort algorithm to sort an array.', 'public static void mergeSort(int[] arr) {\n    if (arr.length <= 1) {\n        return;\n    }\n    int mid = arr.length / 2;\n    int[] left = new int[mid];\n    int[] right = new int[arr.length - mid];\n    \n    for (int i = 0; i < mid; i++) {\n        left[i] = arr[i];\n    }\n    for (int i = mid; i < arr.length; i++) {\n        right[i - mid] = arr[i];\n    }\n    \n    mergeSort(left);\n    mergeSort(right);\n    merge(arr, left, right);\n}', 'public static void mergeSort(int[] arr) {\n    if (arr == null || arr.length <= 1) {\n        return;\n    }\n    int mid = arr.length / 2;\n    int[] left = new int[mid];\n    int[] right = new int[arr.length - mid];\n    \n    for (int i = 0; i < mid; i++) {\n        left[i] = arr[i];\n    }\n    for (int i = mid; i < arr.length; i++) {\n        right[i - mid] = arr[i];\n    }\n    \n    mergeSort(left);\n    mergeSort(right);\n    merge(arr, left, right);\n}', 'The function should handle null input.', 'What happens when the input array is null?', 'Add a check for null input.', 'Consider edge cases like null or empty array.', 10, '{5, 2, 8, 1, 9}', '{1, 2, 5, 8, 9}', '{3, 1, 4, 1, 5}', '{1, 1, 3, 4, 5}', '{}', '{}');

-- C++ Basic Challenges
INSERT INTO cpp_basic (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Count Elements', 'Write a function that counts the number of elements in a vector. Handle edge cases properly.', '#include <vector>\n#include <iostream>\n\nint countElements(std::vector<int>& numbers) {\n    int count = 0;\n    for (int i = 0; i <= numbers.size(); i++) {\n        count++;\n    }\n    return count;\n}', '#include <vector>\n#include <iostream>\n\nint countElements(std::vector<int>& numbers) {\n    return numbers.size();\n}', 'The bug is in the loop condition. Using <= instead of < causes an off-by-one error. Also, we can simply return numbers.size() instead of counting manually.', 'What happens when i equals numbers.size()?', 'Vectors are zero-indexed. If size is 5, valid indices are 0-4, not 0-5.', 'Why count manually when you can use the size() method?', 10, '{1, 2, 3, 4, 5}', '5', '{10, 20}', '2', '{}', '0');

-- C++ Intermediate Challenges
INSERT INTO cpp_intermediate (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Remove Duplicates', 'Write a function that removes duplicate elements from a vector.', '#include <vector>\n#include <iostream>\n\nstd::vector<int> removeDuplicates(std::vector<int>& numbers) {\n    std::vector<int> result;\n    for (int i = 0; i < numbers.size(); i++) {\n        bool found = false;\n        for (int j = 0; j < result.size(); j++) {\n            if (numbers[i] == result[j]) {\n                found = true;\n                break;\n            }\n        }\n        if (!found) {\n            result.push_back(numbers[i]);\n        }\n    }\n    return result;\n}', '#include <vector>\n#include <iostream>\n#include <algorithm>\n\nstd::vector<int> removeDuplicates(std::vector<int>& numbers) {\n    if (numbers.empty()) {\n        return {};\n    }\n    std::vector<int> result;\n    for (int i = 0; i < numbers.size(); i++) {\n        if (std::find(result.begin(), result.end(), numbers[i]) == result.end()) {\n            result.push_back(numbers[i]);\n        }\n    }\n    return result;\n}', 'The function can be optimized using std::find instead of manual loop.', 'Is there a standard library function to find an element?', 'Use std::find to check if an element exists in the result vector.', 'Consider using STL algorithms for better performance.', 10, '{1, 2, 2, 3, 4, 4, 5}', '{1, 2, 3, 4, 5}', '{1, 1, 1}', '{1}', '{}', '{}');

-- C++ Advanced Challenges
INSERT INTO cpp_advanced (challenge_id, title, problem_statement, buggy_code, reference_solution, solution_explanation, hint_1, hint_2, hint_3, learning_objectives, max_score, test_case_1_input, test_case_1_expected, test_case_2_input, test_case_2_expected, test_case_3_input, test_case_3_expected) VALUES
(1, 'Binary Search', 'Implement binary search to find a target number in a sorted vector.', '#include <vector>\n#include <iostream>\n\nint binarySearch(std::vector<int>& arr, int target) {\n    int left = 0;\n    int right = arr.size();\n    while (left < right) {\n        int mid = (left + right) / 2;\n        if (arr[mid] == target) {\n            return mid;\n        } else if (arr[mid] < target) {\n            left = mid;\n        } else {\n            right = mid;\n        }\n    }\n    return -1;\n}', '#include <vector>\n#include <iostream>\n\nint binarySearch(std::vector<int>& arr, int target) {\n    if (arr.empty()) {\n        return -1;\n    }\n    int left = 0;\n    int right = arr.size() - 1;\n    while (left <= right) {\n        int mid = (left + right) / 2;\n        if (arr[mid] == target) {\n            return mid;\n        } else if (arr[mid] < target) {\n            left = mid + 1;\n        } else {\n            right = mid - 1;\n        }\n    }\n    return -1;\n}', 'The bugs are: 1) right should be arr.size() - 1, 2) loop condition should be <=, 3) left should be mid + 1, 4) right should be mid - 1.', 'Check the initial value of right.', 'Look at the loop condition and update logic.', 'Consider how the search space should be reduced.', 10, '{1, 2, 3, 4, 5}', '2', '{1, 3, 5, 7, 9}', '4', '{1, 2, 3, 4, 5}', '-1'); 